# Generated by Django 4.2 on 2025-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementinfo',
            name='settlement_method',
            field=models.CharField(choices=[('cash', '現金決済'), ('card', 'カード決済')], default='cash', max_length=255),
        ),
    ]
