# Generated by Django 4.2 on 2025-01-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementproductlist',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
