# Generated by Django 4.2 on 2025-01-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMApp', '0002_alter_settlementinfo_settlement_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
