# Generated by Django 4.2 on 2025-01-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSMApp', '0003_productinfo_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='unit_price',
        ),
    ]
