# Generated by Django 4.2 on 2025-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMApp', '0004_remove_productinfo_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
